version: "3"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on: 
      - postgres-test

  postgres-test:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "pgtest"
    ports:
      - "15432:5432"
    volumes:
      - /Users/lapedro/Documents/postgres-volumes/stock-bd:/var/lib/postgresql/data